{{- if .Values.components.jaeger -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: {{ include "day23-obs.namespace" . }}
  labels:
    {{- include "day23-obs.labels" . | nindent 4 }}
    app: jaeger
    tier: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        {{- include "day23-obs.labels" . | nindent 8 }}
        app: jaeger
        tier: monitoring
    spec:
      containers:
        - name: jaeger
          image: {{ .Values.jaeger.image }}
          ports:
            - name: ui
              containerPort: 16686
            - name: otlp-grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: {{ .Values.jaeger.otlpEnabled | quote }}
          readinessProbe:
            httpGet: { path: /, port: ui }
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.jaeger.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: {{ include "day23-obs.namespace" . }}
  labels:
    {{- include "day23-obs.labels" . | nindent 4 }}
    app: jaeger
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: ui
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
{{- end }}